平日課題３：計算アプリ　CALC作成
ShunOmine/camp_weekday_task3 pull request #2
Opened 2019-03-04 03:09 UTC by ShunOmine

# 課題詳細
計算アプリ　CALCを作成
問題無く動作したので、push, pull requestを作成

close #1

2019-03-04 03:14 UTC, yuchinagai commented
LGTM

2019-03-04 03:19 UTC, yuchinagai approved these changes
LGTM

2019-03-04 03:20 UTC, yuchinagai approved these changes
LGTM

2019-03-05 04:46 UTC, gaia2013 requested changes
いくつかコメントしましたので ご検討ください！

全体を通しての所感：「簡潔な実装を心掛けてください。」

### 受け入れ基準
- [ ] URLにcalcs/値1/演算子/値2を指定した場合、「値1」、「演算子」、「値2」をパラメータで受け取り、計算します。
  - 例1) /calcs/1/addition/2を指定したらビューに1 + 2の結果である3を表示します。
  - 例2) /calcs/3/subtraction/1を指定したらビューに3 - 1の結果である2を表示します。
- [x] URLは/calcs/までは固定で、それ以降をパラメータで受け取る必要があります。
params[XXX]で受け取った値は文字列として認識されるので、to_iメソッドを使用して数値に変換してから計算する必要があります。
- [ ] コントローラ名はcalcs、アクション名はshowで作成して下さい。

2019-03-05 04:46 UTC, gaia2013 commented on app/controllers/calcs_controller.rb
> +  def addition
複数のアクションに渡って、同じような処理を書くことでcontrollerを肥大化させることは避けてください。
∵可読性や保守性を著しく悪化させます。

2019-03-05 04:46 UTC, gaia2013 commented on app/views/calcs/addition.html.erb
> +<h1>計算アプリ</h1>
controllerのaction同様です。
今回のような小規模アプリケーションの作成において、
同じようなのViewを合理的な理由なく作成することに抵抗は感じないかもしれませんが
アプリケーションがスケールするほど改修時のコストが肥大するので、
ご自身のアプリではその辺りの配慮を心がけてください。

2019-03-05 04:46 UTC, gaia2013 commented on config/routes.rb
> +Rails.application.routes.draw do
名前空間の資源を食い潰すのは避けてください。

2019-03-05 04:46 UTC, gaia2013 commented on .gitignore
> +# See https://help.github.com/articles/ignoring-files for more about ignoring files.
個人的な開発環境の設定ファイルを `.gitignore` へ追加しておいてください。

2019-03-05 04:46 UTC, gaia2013 commented on Gemfile.lock
> +   1.17.1
@yuchinagai 
今回、環境構築で2系（2.xx.x）をおそらく導入しているはずなので、
このtopicブランチの内容をローカルへpullしてきて、アプリを立ち上げた際、
 下記のようなエラーが出たのではと予想しますが、適切に対処し、動作確認できましたか？
（臨機応変に対応できていれば、OKです！◎）
### エラー内容（指定したversionのbundlerを導入していないため）
```
$ bin/rails s
Traceback (most recent call last):
        4: from bin/rails:3:in `<main>'
        3: from bin/rails:3:in `load'
        2: from /Users/hitoshi/ruby-camp/review/intern_omine/camp_weekday_task3/bin/spring:8:in `<top (required)>'
        1: from /Users/hitoshi/.rbenv/versions/2.5.3/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/Users/hitoshi/.rbenv/versions/2.5.3/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- bundler (LoadError)
```
### 対処方法（指定versionのbundlerを導入）
```
$ gem install bundler -v 1.17.1
```

2019-03-05 04:46 UTC, gaia2013 commented on app/controllers/calcs_controller.rb
> +  def addition
paramsで演算子も受け取ってshowアクションで分岐処理を実装してみてください！

2019-03-05 04:56 UTC, merged